# Generated by Django 5.1.7 on 2025-05-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='recursos',
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='descricao',
            field=models.TextField(),
        ),
    ]
