# Generated by Django 5.1.7 on 2025-05-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_alter_reserva_options_alter_reserva_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='recursos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
