# Generated by Django 5.1.3 on 2025-05-24 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_laboratorio_recursos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='status',
        ),
    ]
