# Generated by Django 5.1.3 on 2025-05-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0006_remove_reserva_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('indisponivel', 'Indisponível')], default='indisponivel', max_length=15),
        ),
    ]
