# Generated by Django 5.1.3 on 2025-05-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_reserva_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('indisponivel', 'Indisponível')], default='indisponivel', max_length=20),
        ),
    ]
